generator:
  start:
    package: "github.com/b2wdigital/openbox-go/examples/simple/handler"
    func:    "Start"
  stop:
    package: "github.com/b2wdigital/openbox-go/examples/simple/handler"
    func:    "Stop"
  requestMaps:
    - method:   "GET"
      endpoint: "/test1/:test"
      handler:
        package: "github.com/b2wdigital/openbox-go/examples/simple/handler"
        func:    "Test1"
      httpCode: 200
    - method:   "POST"
      endpoint: "/test2"
      handler:
        package: "github.com/b2wdigital/openbox-go/examples/simple/handler"
        func:    "Test2"
      body:
        package: "github.com/b2wdigital/openbox-go/examples/simple/event"
        struct: "User"
      httpCode: 201
